# Site settings
short_title: "École des Données" 
description: |
  Apprendre à rendre les données utiles, 
  pour vous, et pour les autres. 
  Savoir c'est pouvoir. 
url: "http://ecoledesdonnees.org" # the base hostname & protocol for your site
# baseurl: "http://ecoledesdonnees.org"

github_username: ecoledesdonnees
github_repo: site
paypal: 
contact: 

gems:
  - jekyll-redirect-from

devs:
  -
      name: Sam Smith
      github: smth
  -
      name: Rufus Pollock
      github: rgrp
  -
      name: Paul Walsh
      github: pwalsh

contributors:
  -
      name: Pierre Chrzanowski 		 
      link: https://ecoledesdonnees.github.io/site/
      
  -
      name: Cécile Le Guen
      link: http://jonathangray.org/
  -
      name: Samuel Goëta	
      link: http://timmcnamara.co.nz/
  -
      name: Sylvia Fredriksson
      link: http://poikola.fi/
  -
      name: Agathe Sevegrand
      link: #

supporters:
  -
    name: Open Knowledge France
    logo: 
    footer_logo: OK_LG_LOGO_FRANCE_WHITE_RGB.png
    url: https://okfn.fr/
  -
    name: Open Knowledge International
    logo: 
    footer_logo: okfn-logo-200x206.png
    url: https://okfn.org/


googleanalytics: 
google_verification: 

# Build settings
markdown: kramdown

permalink: pretty

languages:
  -
    - fr
    - Français

meta:
  resources:
    label: resources
    output: true
    has_translation: false
    title: Cours
    filters:
      - Topic
      - Language
      - Region
      - MediaType


defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts

  -
    scope:
      path: "contribute"
    values:
      lang: fr
      section: contribute
      layout: docs
      edit: true
      

related_projects:
  -
      name: SchoolOfData.org
      link: http://schoolofdata.org/
  -
      name: OpenSpending.org
      link: http://openspending.org/
  -
      name: OpenDefinition.org
      link: http://opendefinition.org/
